[toolchain]
channel = "nightly-2023-06-15"
components = [ "rustfmt", "rustc-dev", "rust-std", "clippy", "cargo", "rust-analyzer" ]
# targets = [ "wasm32-unknown-unknown", "thumbv2-none-eabi" ]
# profile = "minimal"
